/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.sean.splugin;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {

    }
}
